version: '2'
services:
    gcpedia:
      build: .
      ports:
        - 8080:80
      depends_on:
        - gcpedia-db
      # uncomment the 'volumes' section to enable a shared volume with docker-compose
      volumes:
        - .:/var/www/html
        - Z:/data:/data:rw
      environment:
        - MEDIAWIKI_SITE_SERVER=http://gcpedia.local:8080/
        - MEDIAWIKI_SITE_NAME=GCPedia
        - MEDIAWIKI_DB_HOST=gcpdedia-db
        - MEDIAWIKI_DB_USER=mediawiki
        - MEDIAWIKI_DB_PASSWORD=gcpedia
        - VIRTUAL_HOST=gcpedia.local

        # uncomment 'MEDIAWIKI_ENABLE_SSL' to enable SSL support
    # - MEDIAWIKI_ENABLE_SSL=true
    gcpedia-db:
        image: library/mysql:5.6
        environment:
            - MYSQL_ROOT_PASSWORD=gcpedia
            - MYSQL_DATABASE=mediawiki
            - MYSQL_USER=mediawiki
            - MYSQL_PASSWORD=gcpedia

# docker build -t gcpedia-apache-php .
# docker run --name gcpedia-mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw -e MYSQL_DATABASE=my_wiki -e MYSQL_USER=wiki -e MYSQL_PASSWORD=password -d mysql
# docker run --name gcpedia -p 8080:80 -v `pwd`:/var/www/html --link gcpedia-mysql:mysql -d gcpedia-apache-php
# CMD curl -s https://getcomposer.org/installer | php &&
